### ISSUE TITLE
Deezer version incorrect/outdated

### ISSUE THREAD

**Issue by kmantel** [JkbLskw/Chocolatey_Packages#1]
Deezer version in Chocolatey is labeled 4.19.20, but version 4.20.21 is downloaded, causing a hash mismatch.

    PS C:\Windows\system32> choco install deezer
    Chocolatey v0.10.15
    Installing the following packages:
    deezer
    By installing you accept licenses for the packages.
    Progress: Downloading deezer 4.19.20... 100%

    deezer v4.19.20 [Approved]
    deezer package files install completed. Performing other installation steps.
    The package deezer wants to run 'chocolateyInstall.ps1'.
    Note: If you don't run this script, the installation will fail.
    Note: To confirm automatically next time, use '-y' or consider:
    choco feature enable -n allowGlobalConfirmation
    Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): a

    File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
    Error - hashes do not match. Actual value was 'B0D5069C2C4B34D1B6FB37A345692DA7164FE97CC63D95A08561B1CFECC34CE8'.
    Downloading Deezer-Desktop
    from 'https://www.deezer.com/desktop/download?platform=win32&architecture=x86'
    Progress: 100% - Completed download of C:\Users\katherine\AppData\Local\Temp\chocolatey\deezer\4.19.20\DeezerDesktopSetup_4.20.21.exe (66.93 MB).
    Download of DeezerDesktopSetup_4.20.21.exe (66.93 MB) completed.
    Error - hashes do not match. Actual value was 'B0D5069C2C4B34D1B6FB37A345692DA7164FE97CC63D95A08561B1CFECC34CE8'.
    ERROR: Checksum for 'C:\Users\katherine\AppData\Local\Temp\chocolatey\deezer\4.19.20\DeezerDesktopSetup_4.20.21.exe' did not meet 'c17d343fad67ba1f093e4477cb8d899c0e33b4717be540f878db0fb93811747a' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
    The install of deezer was NOT successful.
    Error while running 'C:\ProgramData\chocolatey\lib\deezer\tools\chocolateyInstall.ps1'.
    See log for details.

    Chocolatey installed 0/1 packages. 1 packages failed.
    See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

    Failures
    - deezer (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\deezer\tools\chocolateyInstall.ps1'.
    See log for details.

**Comment by JkbLskw** [comment]
Updated to 4.20.21
